config/routes.rb
# config/routes.rb


Rails.application.routes.draw do
  resources :movies, only: [:index, :show]
  get '/search', to: 'search#index', as: 'search_index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
# app/models/movie.rb

class Movie < ApplicationRecord
    paginates_per 20
    # ...
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
# app/controllers/movies_controller.rb

class MoviesController < ApplicationController
    def index
      @movies = Tmdb::Movie.popular
    end
    def show
        @movie = Tmdb::Movie.detail(params[:id])
        @movie.trailer_key = fetch_movie_trailer(params[:id])
        @movie.actors = fetch_movie_actors(params[:id])
        @movie.box_office = fetch_movie_box_office(params[:id])
    end
    
      private
    
    def fetch_movie_trailer(movie_id)
        videos = Tmdb::Movie.videos(movie_id)
        trailer = videos.find { |video| video['type'] == 'Trailer' }
        trailer['key'] if trailer
    end
    
    def fetch_movie_actors(movie_id)
        cast = Tmdb::Movie.cast(movie_id)
        cast.map { |actor| actor['name'] }.join(', ')
    end
    
    def fetch_movie_box_office(movie_id)
        movie_details = Tmdb::Movie.detail(movie_id)
        budget = movie_details['budget']
        revenue = movie_details['revenue']
      
        "Budget: $#{budget.to_i / 1000000}M, Revenue: $#{revenue.to_i / 1000000}M"
    end
      
end
  

app/controllers/search_controller.rb
# app/controllers/search_controller.rb

class SearchController < ApplicationController
    def index
      if params[:query].present?
        @results = Tmdb::Search.movie(params[:query])
        puts @results.inspect # Add this line for debugging
      else
        @results = []
      end
    end
end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_search_form_html.erb
<!-- app/views/layouts/_search_form.html.erb -->

<%= form_tag(search_index_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search for a movie..." %>
  <%= submit_tag "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%# <nav> %>
    <!-- Other navigation items -->
    <%# <%= render 'layouts/search_form' %>
  <%# </nav>  %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<!-- app/views/movies/index.html.erb -->

<h1>Popular Movies</h1>
<ul>
  <% @movies.results.each do |movie| %>
    <li>
      <% if movie.poster_path.present? %>
        <% cache(movie) do %>
          <a href="<%= movie_path(movie.id) %>">
            <img src="https://image.tmdb.org/t/p/w300<%= movie.poster_path %>" alt="<%= movie.title %> Poster">
          </a>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<!-- app/views/movies/show.html.erb -->

<h1><%= @movie.title %></h1>

<% if @movie.poster_path.present? %>
  <img src="https://image.tmdb.org/t/p/w500<%= @movie.poster_path %>" alt="<%= @movie.title %> Poster">
<% end %>

<% if @movie.trailer_key.present? %>
  <h2>Trailer</h2>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @movie.trailer_key %>" frameborder="0" allowfullscreen></iframe>
<% end %>

<p><strong>Overview:</strong> <%= @movie.overview %></p>
<p><strong>Release Date:</strong> <%= @movie.release_date %></p>
<p><strong>Genres:</strong>
  <% @movie.genres.each do |genre| %>
    <%= genre.name %>
    <% unless genre == @movie.genres.last %>, <% end %>
  <% end %>
</p>
<p><strong>Runtime:</strong> <%= @movie.runtime %> minutes</p>
<p><strong>Average Vote:</strong> <%= @movie.vote_average %> (out of 10)</p>
<p><strong>Original Title:</strong> <%= @movie.original_title %></p>
<p><strong>Tagline:</strong> <%= @movie.tagline %></p>
<p><strong>Production Companies:</strong>
  <% @movie.production_companies.each do |company| %>
    <%= company.name %>
    <% unless company == @movie.production_companies.last %>, <% end %>
  <% end %>
</p>
<p><strong>Production Countries:</strong>
  <% @movie.production_countries.each do |country| %>
    <%= country.name %>
    <% unless country == @movie.production_countries.last %>, <% end %>
  <% end %>
</p>
<p><strong>Spoken Languages:</strong>
  <% @movie.spoken_languages.each do |language| %>
    <%= language.name %>
    <% unless language == @movie.spoken_languages.last %>, <% end %>
  <% end %>
</p>

<!-- Display Actors -->
<p><strong>Actors:</strong> <%= @movie.actors %></p>

<!-- Display Box Office -->
<p><strong>Box Office:</strong> <%= @movie.box_office %></p>

<%= link_to 'Back to Movies', movies_path %>

app/views/search/index.html.erb
<!-- app/views/search/index.html.erb -->

<h1>Search for Movies</h1>

<%= form_tag(search_index_path, method: :get) do %>
  <p>
    <%= text_field_tag :query, params[:query], placeholder: "Search for a movie..." %>
    <%= submit_tag "Search" %>
  </p>
<% end %>

<%= link_to 'Popular Movies', movies_path %>

<% if @results.present? && @results["results"].present? %>
  <h2>Search Results:</h2>
  <ul>
    <% @results["results"].each do |result| %>
      <li>
        <%= link_to movie_path(result["id"]) do %>
          <% if result["poster_path"].present? %>
            <img src="https://image.tmdb.org/t/p/w500<%= result["poster_path"] %>" alt="<%= result["title"] %> Poster">
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>